name: Generate Services URLs

on:
  workflow_call:
    inputs:
      deployment-environment:
        required: true
        type: string
    outputs:
      data-service-url:
        description: "Data Service URL"
        value: ${{ jobs.generate-services-urls.outputs.data-service-url }}
      migration-service-url:
        description: "Migration Service URL"
        value: ${{ jobs.generate-services-urls.outputs.migration-service-url }}

jobs:

  generate-services-urls:
    name: Generate Data Service URL
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_ENVIRONMENT: ${{ inputs.deployment-environment }}

    outputs:
      data-service-url: ${{ steps.generate-data-service-url.outputs.data-service-url }}
      migration-service-url: ${{ steps.generate-migration-service-url.outputs.migration-service-url }}

    steps:

      - name: Print Target Environment
        run: echo 'Generating version for ${{ env.DEPLOYMENT_ENVIRONMENT }}...'

      - id: generate-data-service-url
        name: Generate Data Service URL
        run: |
          if env.DEPLOYMENT_ENVIRONMENT == 'Development'
            echo '::set-output name=data-service-url::dev-data-service-url'
          if env.DEPLOYMENT_ENVIRONMENT == 'Staging'
            echo '::set-output name=data-service-url::stg-data-service-url'
          if env.DEPLOYMENT_ENVIRONMENT == 'Production'
            echo '::set-output name=data-service-url::prd-data-service-url'

      - id: generate-migration-service-url
        name: Generate Migration Service URL
        run: |
          if env.DEPLOYMENT_ENVIRONMENT == 'Development'
            env.DEPLOYMENT_ENVIRONMENT == 'Development'
          if env.DEPLOYMENT_ENVIRONMENT == 'Staging'
            echo '::set-output name=migration-service-url::stg-migration-service-url'
          if env.DEPLOYMENT_ENVIRONMENT == 'Production'
            echo '::set-output name=migration-service-url::prd-migration-service-url'
            